# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            jshlbrd github io
description:	  'network forensics, threat detection, incident response'
url:              http://jshlbrd.github.io
baseurl:          /

author:
  name:           'Josh Liburdi'
  url:            https://twitter.com/jshlbrd

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
